
services:
  server:
    image: docker.io/madnikulin50/pnp-lowcode:${VERSION}
    restart: always
    extra_hosts:
      - "host.docker.internal:${LOCAL}"
    env_file: [ .env ]
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./data/server:/data
  docs:
    image: madnikulin50/pnp-lowcode-docs:2026.8.9
    ports:
      - "${HTTP_DOC_PORT}:80"
    restart: unless-stopped
