#!/usr/bin/env python3
"""Generate agent/oui_mobile.go from the IEEE OUI registry (oui.csv).

Usage:
    python3 tools/gen_oui.py /tmp/opencode/oui.csv agent/oui_mobile.go

The generated table maps MAC OUIs (XX:XX:XX) of mobile/consumer-device
vendors (phones, tablets, smart wearables) to their organization name.
It is used by the classifier as one supporting signal among many —
a matching OUI alone never decides a device type.
"""

import csv
import re
import sys

# Substrings matched (case-insensitive) against the OUI organization name.
MOBILE_KEYWORDS = [
    "apple",
    "samsung",
    "xiaomi",
    "huawei device",
    "huawei technologies",
    "honor device",
    "honor technologies",
    "google llc",
    "google, inc",
    "oneplus",
    "oppo",
    "vivo mobile",
    "motorola mobility",
    "moto mobility",
    "lg mobile",
    "lg electronics mobile",
    "hmd global",
    "realme",
    "tcl alcatel mobile",
    "sony mobile",
    "sony ericsson",
    "infinix",
    "tecno mobile",
    "itel mobile",
    "meizu",
    "blackberry",
    "rim mobile",
    "fairphone",
    "essential products",
    "karbonn",
    "micromax",
    "gionee",
    "poco global",
]


def is_mobile(org: str) -> bool:
    low = org.lower()
    for kw in MOBILE_KEYWORDS:
        if kw in low:
            return True
    return False


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    src, dst = sys.argv[1], sys.argv[2]

    entries = {}
    with open(src, newline="", encoding="utf-8") as f:
        for row in csv.reader(f):
            if len(row) < 3 or row[0] not in ("MA-L", "MA-M", "MA-S"):
                continue
            assignment, org = row[1].strip(), row[2].strip()
            if not assignment or not org or not is_mobile(org):
                continue
            prefix = assignment[0:6].upper()
            entries.setdefault(prefix, org)

    lines = []
    lines.append("package agent")
    lines.append("")
    lines.append("// Code generated by tools/gen_oui.py from the IEEE OUI registry.")
    lines.append("// DO NOT EDIT. Regenerate with: python3 tools/gen_oui.py oui.csv agent/oui_mobile.go")
    lines.append("")
    lines.append("// mobileOUI maps MAC OUIs of mobile/consumer-device vendors to their")
    lines.append("// organization name. It is one supporting signal for the classifier;")
    lines.append("// a matching OUI alone never decides a device type (Apple makes laptops,")
    lines.append("// Samsung and LG make TVs, etc.).")
    lines.append("var mobileOUI = map[string]string{")
    for prefix in sorted(entries):
        lines.append('\t"%s": "%s",' % (prefix, entries[prefix]))
    lines.append("}")
    lines.append("")
    lines.append("// mobileVendor returns the organization name for a MAC address if its OUI")
    lines.append('// belongs to a known mobile/consumer vendor, or "" otherwise.')
    lines.append("func mobileVendor(mac string) string {")
    lines.append('\tmac = strings.ToUpper(strings.ReplaceAll(mac, "-", ":"))')
    lines.append("\tfor prefix, org := range mobileOUI {")
    lines.append("\t\tif strings.HasPrefix(mac, prefix) {")
    lines.append("\t\t\treturn org")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append('\treturn ""')
    lines.append("}")

    header = """package agent

// Code generated by tools/gen_oui.py from the IEEE OUI registry.
// DO NOT EDIT. Regenerate with: python3 tools/gen_oui.py oui.csv agent/oui_mobile.go

import "strings"

// mobileOUI maps MAC OUIs of mobile/consumer-device vendors to their
// organization name. It is one supporting signal for the classifier;
// a matching OUI alone never decides a device type (Apple makes laptops,
// Samsung and LG make TVs, etc.).
var mobileOUI = map[string]string{
"""
    footer = """
}

// mobileVendor returns the organization name for a MAC address if its OUI
// belongs to a known mobile/consumer vendor, or "" otherwise.
func mobileVendor(mac string) string {
	mac = strings.ToUpper(strings.ReplaceAll(mac, "-", ":"))
	mac = strings.ReplaceAll(mac, ":", "")
	for prefix, org := range mobileOUI {
		if strings.HasPrefix(mac, prefix) {
			return org
		}
	}
	return ""
}
"""

    with open(dst, "w", encoding="utf-8") as f:
        f.write(header)
        for prefix in sorted(entries):
            f.write('\t"%s": "%s",\n' % (prefix, entries[prefix]))
        f.write(footer)

    print("wrote %d mobile OUI entries -> %s" % (len(entries), dst))
    return 0


if __name__ == "__main__":
    sys.exit(main())